- platform: template
  sensors:
    person1_home_status:
      value_template: "{{states('input_select.person1')}}"
      friendly_name: "Person1 Home Status"
    person2_home_status:
      value_template: "{{states('input_select.person2')}}"
      friendly_name: "Person2 Home Status"
